[package]
name = "hyperltl"
version = "0.1.0"
authors = ["Leander Tentrup <tentrup@react.uni-saarland.de>"]

[dependencies]
pest = "^2.0"         # parser generator
pest_derive = "^2.0"
lazy_static = "1.1.0" # lazy_static! macro
